"""
FakeExecutor: the executor half of the offline loop (SDLC_LLM=fake, python target stack).

Per TaskSpec it writes a trivial module plus a unit test into the sandbox and commits, exactly like a
real executor would: one commit per task on the run branch, files only where the task allows them.
When the task's allowed_files name release artifacts (README, openapi.yaml, Dockerfile, CI workflow) it
writes those too; the OpenAPI document is taken from the Design so the contract stays spec-driven.
The output is just enough for the python gates in policy.yaml to pass: compileall, ruff/mypy, the
architecture test, `pytest tests/unit --cov`, `pytest tests/integration`, and the release checklist.
"""

from __future__ import annotations

import asyncio
import fnmatch
import re
from pathlib import Path
from typing import Any

from ..engine.context import RunContext
from ..models import Design, TaskSpec
from ..models.trace import Kind
from ..sandbox.git import GitSandbox
from .base import Done, ExecResult

RELEASE_FILES = ("README.md", "openapi.yaml", "Dockerfile", ".github/workflows/ci.yml")


def _allowed(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, p) or fnmatch.fnmatch(path, p.replace("**/", "")) for p in patterns)


def _ident(s: str) -> str:
    ident = re.sub(r"\W", "_", s.lower())
    return ident if ident[:1].isalpha() else f"t_{ident}"


class FakeExecutor:
    def render(self, task: TaskSpec, design: Design, existing: set[str]) -> dict[str, str]:
        """Files to write for this task (path -> content). Scaffolding is written once per sandbox."""
        pkg = _ident((design.classes.packages[0].name if design.classes.packages else "app").split(".")[0])
        mod = _ident(task.id)
        out: dict[str, str] = {}

        def once(path: str, content: str) -> None:
            if path not in existing and _allowed(path, task.allowed_files):
                out[path] = content

        module = f"src/{pkg}/{mod}.py"
        if _allowed(module, task.allowed_files):
            out[module] = (
                f'"""{task.title} (fake executor stand-in for task {task.id})."""\n\n'
                "from __future__ import annotations\n\n\n"
                f"def {mod}() -> str:\n"
                f'    """Return the task id; the real implementation of: {task.title}."""\n'
                f'    return "{task.id}"\n'
            )
            out[f"tests/unit/test_{mod}.py"] = (
                "from __future__ import annotations\n\n"
                f"from {pkg}.{mod} import {mod}\n\n\n"
                f"def test_{mod}() -> None:\n"
                f'    assert {mod}() == "{task.id}"\n'
            )
            once(f"src/{pkg}/__init__.py", f'"""{pkg}: generated by the fake executor."""\n')
            once(
                "tests/conftest.py",
                "import sys\nfrom pathlib import Path\n\n"
                'sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))\n',
            )
            for p in design.classes.packages:  # the layering rules refer to these packages
                once(
                    f"src/{p.name.replace('.', '/')}/__init__.py",
                    f'"""{p.name}: {p.classes[0].responsibility if p.classes else ""}"""\n',
                )
            if design.api.operations:
                paths = sorted({o.path for o in design.api.operations})
                once(f"src/{pkg}/app.py", _render_app(design, pkg))
                once(
                    "tests/unit/test_app.py",
                    "from __future__ import annotations\n\n"
                    f"from {pkg}.app import app\n\n\n"
                    "def test_contract_paths_exposed() -> None:\n"
                    f"    assert sorted(app.openapi()['paths']) == {paths!r}\n",
                )
            once(
                "tests/integration/test_smoke.py",
                f"import {pkg}\n\n\ndef test_package_imports() -> None:\n    assert {pkg}.__doc__\n",
            )
        once(
            "README.md",
            f"# {pkg}\n\nGenerated by the fake executor.\n\n## Decisions\n"
            + "".join(f"- {d}\n" for d in design.decisions),
        )
        once("openapi.yaml", design.api.openapi_yaml)
        once(
            "Dockerfile",
            "FROM python:3.12-slim\nWORKDIR /app\nCOPY src /app/src\nENV PYTHONPATH=/app/src\n"
            f'CMD ["python", "-c", "import {pkg}"]\n',
        )
        once(
            ".github/workflows/ci.yml",
            "name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n"
            "      - uses: actions/checkout@v4\n      - run: pip install pytest && pytest -q\n",
        )
        return out

    async def execute(
        self, ctx: RunContext, task: TaskSpec, design: Design, feedback: dict[str, Any] | None
    ) -> ExecResult:
        git = GitSandbox(ctx.sandbox)
        base = await git.base_ref()
        existing = await asyncio.to_thread(_tree, ctx.sandbox)
        files = self.render(task, design, existing)
        for rel, content in files.items():
            await asyncio.to_thread(_write, ctx.sandbox / rel, content)
        changed = await git.changed_files(base)
        sha = await git.commit_task(task.id, task.title, ctx.run_id)
        ctx.emit(Kind.EXECUTOR_CALL, task_id=task.id, actor="fake-executor", payload={"files": changed})
        return Done(
            files_changed=changed,
            tests_added=[f for f in changed if f.startswith("tests/")],
            commit_sha=sha,
            notes="fake executor: trivial module + test",
        )


def _render_app(design: Design, pkg: str) -> str:
    """A FastAPI app whose OpenAPI document is exactly the Design contract (operation ids, paths, codes)."""
    lines = [
        '"""FastAPI app exposing the Design API contract (fake executor)."""',
        "",
        "from __future__ import annotations",
        "",
        "from fastapi import FastAPI, Response",
        "",
        f"app = FastAPI(title={pkg!r})",
    ]
    for op in design.api.operations:
        codes = sorted(op.responses) or [200]
        success = codes[0]
        others = ", ".join(f"{c}: {{'description': {op.responses[c]!r}}}" for c in codes if c != success)
        lines += [
            "",
            "",
            f"@app.{op.method.lower()}({op.path!r}, operation_id={op.operation_id!r}, status_code={success}, "
            f"responses={{{others}}})",
            f"def {_ident(op.operation_id)}() -> Response:",
            f"    return Response(status_code={success})",
        ]
    return "\n".join(lines) + "\n"


def _tree(root: Path) -> set[str]:
    return {str(p.relative_to(root)) for p in root.rglob("*") if p.is_file() and ".git" not in p.parts}


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
