package sdlc;

// Architecture contract generated by the orchestrator from Design.classes.layering_rules.
// Spec version 2.
// Regenerated whenever the design changes; do not edit by hand. Rules of the form "a -> b -> c" are layer
// chains: a class whose package or name matches a layer must not import a class of a higher layer.
// Rules without "->" (for humans only): ['com.example.shortener.analytics.domain must not depend on any other application package (no Spring web, no Kafka, no repository types).', 'com.example.shortener.analytics.repository may depend only on ..analytics.domain; it must not depend on api, outbox, consumer, kafka, recording or retention.', 'com.example.shortener.analytics.api must not depend on ..analytics.outbox, ..analytics.consumer, ..analytics.kafka or ..analytics.retention: the stats endpoint reads aggregates only.', 'com.example.shortener.analytics.recording must not depend on ..analytics.kafka, ..analytics.outbox or any Kafka/producer type; the redirect path performs zero network I/O.', 'No package outside com.example.shortener.analytics.kafka and ..analytics.consumer and ..analytics.config may import org.apache.kafka.. or org.springframework.kafka...', 'com.example.shortener.redirect may depend on com.example.shortener.analytics.recording only; it must not reach into analytics.repository, analytics.domain or analytics.api.', 'Nothing in com.example.shortener.analytics may depend on com.example.shortener.redirect (analytics is a downstream consumer, not an upstream dependency): no cycles between top-level packages.', 'Controllers (@RestController) exist only in ..api packages; @Entity classes exist only in ..domain packages; @Repository / Spring Data interfaces only in ..repository packages.', '@Scheduled methods may exist only in ..analytics.outbox and ..analytics.retention and must run on the dedicated analytics scheduler, never on a request thread.', 'No class may log, return or store a raw client IP: java.net.InetAddress / remote-address values may be referenced only inside ..analytics.recording.IpHasher and the redirect controller that reads the request.', 'Error responses are produced only by the existing global exception handler as application/problem+json; controllers must not build ad-hoc error bodies.']

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

class ArchitectureTest {

  static final List<List<String>> CHAINS = List.of(List.of("api", "repository", "domain"));
  static final Pattern PKG = Pattern.compile("^\\s*package\\s+([\\w.]+)\\s*;", Pattern.MULTILINE);
  static final Pattern IMP =
      Pattern.compile("^\\s*import\\s+(?:static\\s+)?([\\w.]+)\\s*;", Pattern.MULTILINE);

  @Test
  void layeringRules() throws IOException {
    Path root = Path.of("src/main/java");
    if (!Files.isDirectory(root) || CHAINS.isEmpty()) {
      return;
    }
    Map<String, List<String>> imports = new HashMap<>();
    try (Stream<Path> files = Files.walk(root)) {
      for (Path p : files.filter(f -> f.toString().endsWith(".java")).toList()) {
        String src = Files.readString(p);
        Matcher pm = PKG.matcher(src);
        String pkg = pm.find() ? pm.group(1) : "";
        String fqcn = pkg + "." + p.getFileName().toString().replace(".java", "");
        List<String> imps = new ArrayList<>();
        Matcher im = IMP.matcher(src);
        while (im.find()) {
          imps.add(im.group(1));
        }
        imports.put(fqcn, imps);
      }
    }
    List<String> violations = new ArrayList<>();
    for (List<String> chain : CHAINS) {
      for (Map.Entry<String, List<String>> e : imports.entrySet()) {
        int from = layerOf(e.getKey(), chain);
        if (from < 0) {
          continue;
        }
        for (String imp : e.getValue()) {
          int to = layerOf(imp, chain);
          if (to >= 0 && to < from) {
            violations.add(
                e.getKey() + " -> " + imp + " (" + chain.get(from) + " must not depend on "
                    + chain.get(to) + ")");
          }
        }
      }
    }
    assertTrue(violations.isEmpty(), "layering rules violated:\n" + String.join("\n", violations));
  }

  static int layerOf(String fqcn, List<String> chain) {
    String lower = fqcn.toLowerCase();
    for (int i = 0; i < chain.size(); i++) {
      String layer = chain.get(i);
      if (lower.contains("." + layer + ".") || lower.endsWith("." + layer) || lower.endsWith(layer)) {
        return i;
      }
    }
    return -1;
  }
}
