package sdlc;

// Architecture contract generated by the orchestrator from Design.classes.layering_rules.
// Spec version 2.
// Regenerated whenever the design changes; do not edit by hand. Rules of the form "a -> b -> c" are layer
// chains: a class whose package or name matches a layer must not import a class of a higher layer.
// Rules without "->" (for humans only): ['domain must not depend on api.*, write, read or codegen; it knows only JPA and CodeSource.', 'config is a leaf: ShortenerProperties depends on nothing inside the application.', 'write must not depend on read and read must not depend on write; the two deployment surfaces stay independently registrable via @Profile.', 'Only classes in write and read may carry web annotations (@RestController/@RequestMapping); services and repositories stay framework-web-free.', 'Only RedisBatchCounterSource and RedisUrlCache may reference Spring Data Redis types; all other code talks to the CounterSource and UrlCache interfaces.', 'Infrastructure failures (Redis) are handled at the boundary class that owns the technology: RedisUrlCache swallows and logs, RedisBatchCounterSource throws and ShortCodeAllocator decides the fallback. Controllers never catch infrastructure exceptions.', 'No controller builds an error body; every non-2xx response is produced by GlobalExceptionHandler as application/problem+json.', 'Test sources in com.example.shortener.it may depend on all production packages; no production package may depend on test sources.', 'No cyclic package dependencies (enforced by the provisioned sdlc.ArchitectureTest).']

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

class ArchitectureTest {

  static final List<List<String>> CHAINS = List.of(List.of("web", "service", "infrastructure"));
  static final Pattern PKG = Pattern.compile("^\\s*package\\s+([\\w.]+)\\s*;", Pattern.MULTILINE);
  static final Pattern IMP =
      Pattern.compile("^\\s*import\\s+(?:static\\s+)?([\\w.]+)\\s*;", Pattern.MULTILINE);

  @Test
  void layeringRules() throws IOException {
    Path root = Path.of("src/main/java");
    if (!Files.isDirectory(root) || CHAINS.isEmpty()) {
      return;
    }
    Map<String, List<String>> imports = new HashMap<>();
    try (Stream<Path> files = Files.walk(root)) {
      for (Path p : files.filter(f -> f.toString().endsWith(".java")).toList()) {
        String src = Files.readString(p);
        Matcher pm = PKG.matcher(src);
        String pkg = pm.find() ? pm.group(1) : "";
        String fqcn = pkg + "." + p.getFileName().toString().replace(".java", "");
        List<String> imps = new ArrayList<>();
        Matcher im = IMP.matcher(src);
        while (im.find()) {
          imps.add(im.group(1));
        }
        imports.put(fqcn, imps);
      }
    }
    List<String> violations = new ArrayList<>();
    for (List<String> chain : CHAINS) {
      for (Map.Entry<String, List<String>> e : imports.entrySet()) {
        int from = layerOf(e.getKey(), chain);
        if (from < 0) {
          continue;
        }
        for (String imp : e.getValue()) {
          int to = layerOf(imp, chain);
          if (to >= 0 && to < from) {
            violations.add(
                e.getKey() + " -> " + imp + " (" + chain.get(from) + " must not depend on "
                    + chain.get(to) + ")");
          }
        }
      }
    }
    assertTrue(violations.isEmpty(), "layering rules violated:\n" + String.join("\n", violations));
  }

  static int layerOf(String fqcn, List<String> chain) {
    String lower = fqcn.toLowerCase();
    for (int i = 0; i < chain.size(); i++) {
      String layer = chain.get(i);
      if (lower.contains("." + layer + ".") || lower.endsWith("." + layer) || lower.endsWith(layer)) {
        return i;
      }
    }
    return -1;
  }
}
