-- V2: click analytics persistence (task T2; AC-1, AC-6, AC-7, AC-10, AC-12).
-- Additive, forward-only Flyway migration: creates four new tables and touches nothing that V1 created.
-- Every timestamp is timestamptz and is written in UTC by the application; click_stats_daily.day is the
-- UTC calendar day of the click. Only a salted SHA-256 hex digest of the client address is ever stored
-- (hashed_ip); no column holds the address itself or any other personal data.

-- Transactional outbox for click events recorded on the redirect path and relayed to Kafka later.
CREATE TABLE click_outbox (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key varchar(128)  NOT NULL,
    short_code      varchar(32)   NOT NULL,
    occurred_at     timestamptz   NOT NULL,
    hashed_ip       varchar(64)   NOT NULL,
    referrer_host   varchar(255)  NULL,
    status          varchar(16)   NOT NULL DEFAULT 'PENDING',
    attempts        integer       NOT NULL DEFAULT 0,
    next_attempt_at timestamptz   NOT NULL,
    published_at    timestamptz   NULL,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_click_outbox PRIMARY KEY (id),
    CONSTRAINT uq_click_outbox_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT click_outbox_status_chk CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT click_outbox_hashed_ip_chk CHECK (hashed_ip ~ '^[0-9a-f]{64}$'),
    CONSTRAINT click_outbox_attempts_chk CHECK (attempts >= 0)
);

-- Relay scan: SELECT ... WHERE status = 'PENDING' AND next_attempt_at <= now() ... FOR UPDATE SKIP LOCKED.
CREATE INDEX idx_click_outbox_status_next_attempt_at ON click_outbox (status, next_attempt_at);
-- Retention scan: purge rows whose occurred_at is older than analytics.retention.days.
CREATE INDEX idx_click_outbox_occurred_at ON click_outbox (occurred_at);

-- Per-link aggregate maintained by the Kafka consumer (one row per short code).
CREATE TABLE click_stats (
    short_code      varchar(32)   NOT NULL,
    total_clicks    bigint        NOT NULL DEFAULT 0,
    last_clicked_at timestamptz   NULL,
    updated_at      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_click_stats PRIMARY KEY (short_code),
    CONSTRAINT click_stats_total_clicks_chk CHECK (total_clicks >= 0)
);

-- Per-link, per-UTC-day aggregate.
CREATE TABLE click_stats_daily (
    short_code      varchar(32)   NOT NULL,
    day             date          NOT NULL,
    count           bigint        NOT NULL DEFAULT 0,
    CONSTRAINT pk_click_stats_daily PRIMARY KEY (short_code, day),
    CONSTRAINT click_stats_daily_count_chk CHECK (count >= 0)
);

-- Consumer-side dedupe: an event whose key is already here has been applied to the aggregates.
CREATE TABLE processed_click_event (
    idempotency_key varchar(128)  NOT NULL,
    processed_at    timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_processed_click_event PRIMARY KEY (idempotency_key)
);

COMMENT ON COLUMN click_outbox.hashed_ip IS 'Salted SHA-256 hex digest (64 lowercase hex chars) of the client address; the address itself is never stored';
COMMENT ON COLUMN click_outbox.status IS 'PENDING = awaiting relay, PUBLISHED = acknowledged by Kafka, FAILED = retries exhausted';
COMMENT ON COLUMN click_stats_daily.day IS 'UTC calendar day of the clicks counted in this row';
