/*
 * OpenApiContractIT.java — parity between the committed openapi.yaml and the running application.
 *
 * Layer: test (integration). Pins AC-15's "committed OpenAPI document matches the implemented
 * endpoints": the YAML that springdoc generates from the live context (GET /v3/api-docs.yaml) is
 * compared with src/main/resources/openapi.yaml path by path, operation by operation and status
 * code by status code (plus operationId, request-body media types, parameters, response media
 * types and headers, response schema references, component schema property names and required
 * lists). A second test pins the committed document's exact content independently of the app.
 * Technique: Spring Boot test on Testcontainers (inherited; the database is only needed to boot),
 * SnakeYAML parsing, hand-written structural diff. Requires Docker; run with ./mvnw -Pit verify.
 */
package com.example.shortener.it;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.yaml.snakeyaml.Yaml;

/**
 * Contract parity (AC-15): the committed {@code src/main/resources/openapi.yaml} must describe
 * exactly what the running application exposes. The document generated by springdoc from the live
 * context is compared with the committed one operation by operation, status code by status code
 * (plus media types, response headers, parameters, request bodies and schema properties); any drift
 * fails the build with the list of differences.
 *
 * <p>Fixture strategy: the shared default-profile application from {@link AbstractIntegrationTest}
 * (both surfaces registered, so both operations appear in the live document). The committed file is
 * read from the classpath, the live one over HTTP; both are parsed with SnakeYAML into nested maps
 * and walked by the private {@code compare*} helpers, which collect human-readable drift lines
 * instead of failing at the first difference. Descriptions, examples, {@code info} and {@code
 * servers} are intentionally not compared, so wording may change without touching this test.
 *
 * <p>Removing this class would let the committed contract and the code drift silently: a new status
 * code, a renamed JSON property or a dropped response header would no longer fail the build, and
 * the README's promise that the file cannot drift would be false.
 */
class OpenApiContractIT extends AbstractIntegrationTest {

  /** Classpath name of the committed contract (from src/main/resources). */
  private static final String COMMITTED_DOCUMENT = "openapi.yaml";

  /** springdoc's YAML endpoint; the same content the -Pit build dumps to target/openapi.yaml. */
  private static final String API_DOCS_PATH = "/v3/api-docs.yaml";

  /**
   * Given the committed and the live document, when their paths and component schemas are compared
   * structurally, then the list of drift messages is empty (AC-15).
   */
  @Test
  void committedDocumentMatchesTheRunningApplication() {
    Map<String, Object> committed = committedDocument();
    Map<String, Object> live = liveDocument();

    List<String> drift = new ArrayList<>();
    comparePaths(map(committed.get("paths")), map(live.get("paths")), drift);
    compareSchemas(
        map(map(committed.get("components")).get("schemas")),
        map(map(live.get("components")).get("schemas")),
        drift);

    assertThat(drift)
        .as("src/main/resources/openapi.yaml drifted from the running application")
        .isEmpty();
  }

  /**
   * Given only the committed document, when inspected, then it describes exactly {@code POST
   * /api/v1/urls} ({@code createShortUrl}: 201 JSON, 400/409/500 problem+json, JSON request body),
   * {@code GET /{short_code}} ({@code redirectToLongUrl}: 302 with Location and Cache-Control
   * headers and no body, 404/410/500 problem+json) and the additive {@code GET
   * /api/v1/urls/{short_code}/stats} ({@code getUrlClickStats}: 200 JSON, 404/500 problem+json,
   * {@code short_code} path parameter), and the component schemas carry the contract's snake_case
   * property names. This pins the README's endpoint tables independently of what springdoc happens
   * to generate.
   */
  @Test
  void committedDocumentDescribesExactlyTheThreeOperations() {
    Map<String, Object> paths = map(committedDocument().get("paths"));

    assertThat(paths.keySet())
        .containsExactlyInAnyOrder(
            "/api/v1/urls", "/{short_code}", "/api/v1/urls/{short_code}/stats");

    Map<String, Object> statsItem = map(paths.get("/api/v1/urls/{short_code}/stats"));
    Map<String, Object> statsOp = map(statsItem.get("get"));
    assertThat(statsItem.keySet()).containsExactly("get");
    assertThat(statsOp.get("operationId")).isEqualTo("getUrlClickStats");
    assertThat(statsOp).doesNotContainKey("requestBody");
    assertThat(parameterNames(statsOp.get("parameters")))
        .containsExactly("path:short_code:required=true");
    assertThat(map(statsOp.get("responses")).keySet())
        .containsExactlyInAnyOrder("200", "404", "500");
    assertThat(map(map(map(statsOp.get("responses")).get("200")).get("content")).keySet())
        .containsExactly("application/json");
    for (String status : List.of("404", "500")) {
      assertThat(map(map(map(statsOp.get("responses")).get(status)).get("content")).keySet())
          .as("getUrlClickStats %s", status)
          .containsExactly("application/problem+json");
    }

    Map<String, Object> create = map(map(paths.get("/api/v1/urls")).get("post"));
    assertThat(map(paths.get("/api/v1/urls")).keySet()).containsExactly("post");
    assertThat(create.get("operationId")).isEqualTo("createShortUrl");
    assertThat(map(create.get("responses")).keySet())
        .containsExactlyInAnyOrder("201", "400", "409", "500");
    assertThat(map(map(create.get("requestBody")).get("content")).keySet())
        .containsExactly("application/json");
    assertThat(map(map(map(create.get("responses")).get("201")).get("content")).keySet())
        .containsExactly("application/json");
    for (String status : List.of("400", "409", "500")) {
      assertThat(map(map(map(create.get("responses")).get(status)).get("content")).keySet())
          .as("createShortUrl %s", status)
          .containsExactly("application/problem+json");
    }

    Map<String, Object> redirect = map(map(paths.get("/{short_code}")).get("get"));
    assertThat(map(paths.get("/{short_code}")).keySet()).containsExactly("get");
    assertThat(redirect.get("operationId")).isEqualTo("redirectToLongUrl");
    assertThat(map(redirect.get("responses")).keySet())
        .containsExactlyInAnyOrder("302", "404", "410", "500");
    Map<String, Object> found = map(map(redirect.get("responses")).get("302"));
    assertThat(map(found.get("headers")).keySet())
        .containsExactlyInAnyOrder("Location", "Cache-Control");
    assertThat(found).doesNotContainKey("content");
    for (String status : List.of("404", "410", "500")) {
      assertThat(map(map(map(redirect.get("responses")).get(status)).get("content")).keySet())
          .as("redirectToLongUrl %s", status)
          .containsExactly("application/problem+json");
    }

    Map<String, Object> schemas = map(map(committedDocument().get("components")).get("schemas"));
    assertThat(map(map(schemas.get("CreateUrlRequest")).get("properties")).keySet())
        .containsExactlyInAnyOrder("long_url", "custom_alias", "expiration_date");
    assertThat(map(map(schemas.get("CreateUrlResponse")).get("properties")).keySet())
        .containsExactlyInAnyOrder(
            "short_url", "short_code", "long_url", "expires_at", "code_source");
    assertThat(schemas).containsKey("ProblemDetail");
    assertThat(map(map(schemas.get("ClickStatsResponse")).get("properties")).keySet())
        .containsExactlyInAnyOrder("total_clicks", "last_clicked_at", "as_of", "clicks_by_day");
    assertThat(map(map(schemas.get("ClickStatsDayEntry")).get("properties")).keySet())
        .containsExactlyInAnyOrder("date", "count");
  }

  // ---------------------------------------------------------------------------------------------
  // Documents
  // ---------------------------------------------------------------------------------------------

  /**
   * Loads and parses the committed contract from the classpath.
   *
   * @return the top-level YAML object; fails the test if the resource is missing
   */
  private static Map<String, Object> committedDocument() {
    ClassPathResource resource = new ClassPathResource(COMMITTED_DOCUMENT);
    assertThat(resource.exists()).as("committed %s on the classpath", COMMITTED_DOCUMENT).isTrue();
    try (InputStream in = resource.getInputStream()) {
      Object parsed = new Yaml().load(in);
      assertThat(parsed).isInstanceOf(Map.class);
      return map(parsed);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  /**
   * Fetches and parses the document springdoc generates from the running application.
   *
   * @return the top-level YAML object; fails the test unless the endpoint answers 200
   */
  private Map<String, Object> liveDocument() {
    HttpResponse<String> response = get(API_DOCS_PATH);
    assertThat(response.statusCode()).as("GET %s", API_DOCS_PATH).isEqualTo(200);
    return json(response.body());
  }

  // ---------------------------------------------------------------------------------------------
  // Comparison
  // ---------------------------------------------------------------------------------------------

  /**
   * Compares the {@code paths} objects: every path and HTTP method must exist on both sides; for
   * pairs present on both, delegates to {@link #compareOperation}.
   *
   * @param committed {@code paths} of the committed document
   * @param live {@code paths} of the live document
   * @param drift accumulator for human-readable differences
   */
  private static void comparePaths(
      Map<String, Object> committed, Map<String, Object> live, List<String> drift) {
    for (String path : union(committed.keySet(), live.keySet())) {
      if (!committed.containsKey(path)) {
        drift.add("path " + path + " is exposed by the application but not documented");
        continue;
      }
      if (!live.containsKey(path)) {
        drift.add("path " + path + " is documented but not exposed by the application");
        continue;
      }
      Map<String, Object> committedItem = map(committed.get(path));
      Map<String, Object> liveItem = map(live.get(path));
      for (String method : union(committedItem.keySet(), liveItem.keySet())) {
        String operation = method.toUpperCase() + " " + path;
        if (!committedItem.containsKey(method)) {
          drift.add(operation + " is exposed by the application but not documented");
          continue;
        }
        if (!liveItem.containsKey(method)) {
          drift.add(operation + " is documented but not exposed by the application");
          continue;
        }
        compareOperation(
            operation, map(committedItem.get(method)), map(liveItem.get(method)), drift);
      }
    }
  }

  /**
   * Compares one operation: operationId, request-body media types and {@code required} flag,
   * parameter set (in/name/required), and for every status code present on either side the media
   * types, header names and per-media-type schema object.
   *
   * @param operation label such as {@code "POST /api/v1/urls"} used in drift messages
   * @param committed the committed operation object
   * @param live the live operation object
   * @param drift accumulator for human-readable differences
   */
  private static void compareOperation(
      String operation,
      Map<String, Object> committed,
      Map<String, Object> live,
      List<String> drift) {
    compareValue(
        operation + " operationId", committed.get("operationId"), live.get("operationId"), drift);
    compareKeys(
        operation + " request body media types",
        map(map(committed.get("requestBody")).get("content")).keySet(),
        map(map(live.get("requestBody")).get("content")).keySet(),
        drift);
    compareValue(
        operation + " request body required",
        map(committed.get("requestBody")).get("required"),
        map(live.get("requestBody")).get("required"),
        drift);
    compareKeys(
        operation + " parameters",
        parameterNames(committed.get("parameters")),
        parameterNames(live.get("parameters")),
        drift);

    Map<String, Object> committedResponses = map(committed.get("responses"));
    Map<String, Object> liveResponses = map(live.get("responses"));
    for (String status : union(committedResponses.keySet(), liveResponses.keySet())) {
      String response = operation + " -> " + status;
      if (!committedResponses.containsKey(status)) {
        drift.add(response + " is exposed by the application but not documented");
        continue;
      }
      if (!liveResponses.containsKey(status)) {
        drift.add(response + " is documented but not exposed by the application");
        continue;
      }
      Map<String, Object> committedResponse = map(committedResponses.get(status));
      Map<String, Object> liveResponse = map(liveResponses.get(status));
      compareKeys(
          response + " media types",
          map(committedResponse.get("content")).keySet(),
          map(liveResponse.get("content")).keySet(),
          drift);
      compareKeys(
          response + " headers",
          map(committedResponse.get("headers")).keySet(),
          map(liveResponse.get("headers")).keySet(),
          drift);
      for (String mediaType : map(liveResponse.get("content")).keySet()) {
        compareValue(
            response + " " + mediaType + " schema",
            map(map(committedResponse.get("content")).get(mediaType)).get("schema"),
            map(map(liveResponse.get("content")).get(mediaType)).get("schema"),
            drift);
      }
    }
  }

  /**
   * Compares {@code components.schemas}: the set of schema names, and for each schema present on
   * both sides its property names and {@code required} list (types, formats and patterns are not
   * compared).
   *
   * @param committed committed schemas by name
   * @param live live schemas by name
   * @param drift accumulator for human-readable differences
   */
  private static void compareSchemas(
      Map<String, Object> committed, Map<String, Object> live, List<String> drift) {
    compareKeys("component schemas", committed.keySet(), live.keySet(), drift);
    for (String name : union(committed.keySet(), live.keySet())) {
      if (!committed.containsKey(name) || !live.containsKey(name)) {
        continue;
      }
      Map<String, Object> committedSchema = map(committed.get(name));
      Map<String, Object> liveSchema = map(live.get(name));
      compareKeys(
          "schema " + name + " properties",
          map(committedSchema.get("properties")).keySet(),
          map(liveSchema.get("properties")).keySet(),
          drift);
      compareKeys(
          "schema " + name + " required",
          list(committedSchema.get("required")),
          list(liveSchema.get("required")),
          drift);
    }
  }

  /**
   * Records a drift line when two key collections differ as sorted sets (order-insensitive).
   *
   * @param what label for the drift message
   * @param committed keys from the committed document
   * @param live keys from the live document
   * @param drift accumulator
   */
  private static void compareKeys(
      String what, Collection<String> committed, Collection<String> live, List<String> drift) {
    Set<String> documented = new TreeSet<>(committed);
    Set<String> exposed = new TreeSet<>(live);
    if (!documented.equals(exposed)) {
      drift.add(what + ": documented " + documented + " but application exposes " + exposed);
    }
  }

  /**
   * Records a drift line when two scalar or nested values are not {@code equals} (null-safe).
   *
   * @param what label for the drift message
   * @param committed value from the committed document
   * @param live value from the live document
   * @param drift accumulator
   */
  private static void compareValue(String what, Object committed, Object live, List<String> drift) {
    if (committed == null ? live != null : !committed.equals(live)) {
      drift.add(what + ": documented " + committed + " but application exposes " + live);
    }
  }

  /**
   * Reduces an OpenAPI {@code parameters} list to comparable {@code in:name:required=...} tokens.
   *
   * @param parameters the raw list, or anything else (treated as no parameters)
   * @return the tokens in document order
   */
  private static Set<String> parameterNames(Object parameters) {
    Set<String> names = new LinkedHashSet<>();
    if (parameters instanceof List<?> list) {
      for (Object parameter : list) {
        Map<String, Object> p = map(parameter);
        names.add(p.get("in") + ":" + p.get("name") + ":required=" + p.get("required"));
      }
    }
    return names;
  }

  /**
   * Sorted union of two key sets, so both documents are walked in one deterministic pass.
   *
   * @param first keys of one side
   * @param second keys of the other side
   * @return all keys, sorted
   */
  private static Set<String> union(Set<String> first, Set<String> second) {
    Set<String> union = new TreeSet<>(first);
    union.addAll(second);
    return union;
  }

  /**
   * Null-tolerant view of a YAML node as a map; anything that is not a map becomes an empty map so
   * missing sections compare as "nothing" instead of throwing.
   *
   * @param value any parsed YAML node
   * @return the map, or an empty immutable map
   */
  @SuppressWarnings("unchecked")
  private static Map<String, Object> map(Object value) {
    return value instanceof Map<?, ?> m ? (Map<String, Object>) m : Map.of();
  }

  /**
   * Null-tolerant view of a YAML node as a list of strings (used for {@code required}).
   *
   * @param value any parsed YAML node
   * @return the items as strings, or an empty list
   */
  private static List<String> list(Object value) {
    List<String> result = new ArrayList<>();
    if (value instanceof List<?> l) {
      for (Object item : l) {
        result.add(String.valueOf(item));
      }
    }
    return result;
  }
}
