package com.example.shortener.it;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.yaml.snakeyaml.Yaml;

/**
 * Contract parity (AC-15): the committed {@code src/main/resources/openapi.yaml} must describe
 * exactly what the running application exposes. The document generated by springdoc from the live
 * context is compared with the committed one operation by operation, status code by status code
 * (plus media types, response headers, parameters, request bodies and schema properties); any drift
 * fails the build with the list of differences.
 */
class OpenApiContractIT extends AbstractIntegrationTest {

  private static final String COMMITTED_DOCUMENT = "openapi.yaml";
  private static final String API_DOCS_PATH = "/v3/api-docs.yaml";

  @Test
  void committedDocumentMatchesTheRunningApplication() {
    Map<String, Object> committed = committedDocument();
    Map<String, Object> live = liveDocument();

    List<String> drift = new ArrayList<>();
    comparePaths(map(committed.get("paths")), map(live.get("paths")), drift);
    compareSchemas(
        map(map(committed.get("components")).get("schemas")),
        map(map(live.get("components")).get("schemas")),
        drift);

    assertThat(drift)
        .as("src/main/resources/openapi.yaml drifted from the running application")
        .isEmpty();
  }

  @Test
  void committedDocumentDescribesExactlyTheTwoOperations() {
    Map<String, Object> paths = map(committedDocument().get("paths"));

    assertThat(paths.keySet()).containsExactlyInAnyOrder("/api/v1/urls", "/{short_code}");

    Map<String, Object> create = map(map(paths.get("/api/v1/urls")).get("post"));
    assertThat(map(paths.get("/api/v1/urls")).keySet()).containsExactly("post");
    assertThat(create.get("operationId")).isEqualTo("createShortUrl");
    assertThat(map(create.get("responses")).keySet())
        .containsExactlyInAnyOrder("201", "400", "409", "500");
    assertThat(map(map(create.get("requestBody")).get("content")).keySet())
        .containsExactly("application/json");
    assertThat(map(map(map(create.get("responses")).get("201")).get("content")).keySet())
        .containsExactly("application/json");
    for (String status : List.of("400", "409", "500")) {
      assertThat(map(map(map(create.get("responses")).get(status)).get("content")).keySet())
          .as("createShortUrl %s", status)
          .containsExactly("application/problem+json");
    }

    Map<String, Object> redirect = map(map(paths.get("/{short_code}")).get("get"));
    assertThat(map(paths.get("/{short_code}")).keySet()).containsExactly("get");
    assertThat(redirect.get("operationId")).isEqualTo("redirectToLongUrl");
    assertThat(map(redirect.get("responses")).keySet())
        .containsExactlyInAnyOrder("302", "404", "410", "500");
    Map<String, Object> found = map(map(redirect.get("responses")).get("302"));
    assertThat(map(found.get("headers")).keySet())
        .containsExactlyInAnyOrder("Location", "Cache-Control");
    assertThat(found).doesNotContainKey("content");
    for (String status : List.of("404", "410", "500")) {
      assertThat(map(map(map(redirect.get("responses")).get(status)).get("content")).keySet())
          .as("redirectToLongUrl %s", status)
          .containsExactly("application/problem+json");
    }

    Map<String, Object> schemas = map(map(committedDocument().get("components")).get("schemas"));
    assertThat(map(map(schemas.get("CreateUrlRequest")).get("properties")).keySet())
        .containsExactlyInAnyOrder("long_url", "custom_alias", "expiration_date");
    assertThat(map(map(schemas.get("CreateUrlResponse")).get("properties")).keySet())
        .containsExactlyInAnyOrder(
            "short_url", "short_code", "long_url", "expires_at", "code_source");
    assertThat(schemas).containsKey("ProblemDetail");
  }

  // ---------------------------------------------------------------------------------------------
  // Documents
  // ---------------------------------------------------------------------------------------------

  private static Map<String, Object> committedDocument() {
    ClassPathResource resource = new ClassPathResource(COMMITTED_DOCUMENT);
    assertThat(resource.exists()).as("committed %s on the classpath", COMMITTED_DOCUMENT).isTrue();
    try (InputStream in = resource.getInputStream()) {
      Object parsed = new Yaml().load(in);
      assertThat(parsed).isInstanceOf(Map.class);
      return map(parsed);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private Map<String, Object> liveDocument() {
    HttpResponse<String> response = get(API_DOCS_PATH);
    assertThat(response.statusCode()).as("GET %s", API_DOCS_PATH).isEqualTo(200);
    return json(response.body());
  }

  // ---------------------------------------------------------------------------------------------
  // Comparison
  // ---------------------------------------------------------------------------------------------

  private static void comparePaths(
      Map<String, Object> committed, Map<String, Object> live, List<String> drift) {
    for (String path : union(committed.keySet(), live.keySet())) {
      if (!committed.containsKey(path)) {
        drift.add("path " + path + " is exposed by the application but not documented");
        continue;
      }
      if (!live.containsKey(path)) {
        drift.add("path " + path + " is documented but not exposed by the application");
        continue;
      }
      Map<String, Object> committedItem = map(committed.get(path));
      Map<String, Object> liveItem = map(live.get(path));
      for (String method : union(committedItem.keySet(), liveItem.keySet())) {
        String operation = method.toUpperCase() + " " + path;
        if (!committedItem.containsKey(method)) {
          drift.add(operation + " is exposed by the application but not documented");
          continue;
        }
        if (!liveItem.containsKey(method)) {
          drift.add(operation + " is documented but not exposed by the application");
          continue;
        }
        compareOperation(
            operation, map(committedItem.get(method)), map(liveItem.get(method)), drift);
      }
    }
  }

  private static void compareOperation(
      String operation,
      Map<String, Object> committed,
      Map<String, Object> live,
      List<String> drift) {
    compareValue(
        operation + " operationId", committed.get("operationId"), live.get("operationId"), drift);
    compareKeys(
        operation + " request body media types",
        map(map(committed.get("requestBody")).get("content")).keySet(),
        map(map(live.get("requestBody")).get("content")).keySet(),
        drift);
    compareValue(
        operation + " request body required",
        map(committed.get("requestBody")).get("required"),
        map(live.get("requestBody")).get("required"),
        drift);
    compareKeys(
        operation + " parameters",
        parameterNames(committed.get("parameters")),
        parameterNames(live.get("parameters")),
        drift);

    Map<String, Object> committedResponses = map(committed.get("responses"));
    Map<String, Object> liveResponses = map(live.get("responses"));
    for (String status : union(committedResponses.keySet(), liveResponses.keySet())) {
      String response = operation + " -> " + status;
      if (!committedResponses.containsKey(status)) {
        drift.add(response + " is exposed by the application but not documented");
        continue;
      }
      if (!liveResponses.containsKey(status)) {
        drift.add(response + " is documented but not exposed by the application");
        continue;
      }
      Map<String, Object> committedResponse = map(committedResponses.get(status));
      Map<String, Object> liveResponse = map(liveResponses.get(status));
      compareKeys(
          response + " media types",
          map(committedResponse.get("content")).keySet(),
          map(liveResponse.get("content")).keySet(),
          drift);
      compareKeys(
          response + " headers",
          map(committedResponse.get("headers")).keySet(),
          map(liveResponse.get("headers")).keySet(),
          drift);
      for (String mediaType : map(liveResponse.get("content")).keySet()) {
        compareValue(
            response + " " + mediaType + " schema",
            map(map(committedResponse.get("content")).get(mediaType)).get("schema"),
            map(map(liveResponse.get("content")).get(mediaType)).get("schema"),
            drift);
      }
    }
  }

  private static void compareSchemas(
      Map<String, Object> committed, Map<String, Object> live, List<String> drift) {
    compareKeys("component schemas", committed.keySet(), live.keySet(), drift);
    for (String name : union(committed.keySet(), live.keySet())) {
      if (!committed.containsKey(name) || !live.containsKey(name)) {
        continue;
      }
      Map<String, Object> committedSchema = map(committed.get(name));
      Map<String, Object> liveSchema = map(live.get(name));
      compareKeys(
          "schema " + name + " properties",
          map(committedSchema.get("properties")).keySet(),
          map(liveSchema.get("properties")).keySet(),
          drift);
      compareKeys(
          "schema " + name + " required",
          list(committedSchema.get("required")),
          list(liveSchema.get("required")),
          drift);
    }
  }

  private static void compareKeys(
      String what, Collection<String> committed, Collection<String> live, List<String> drift) {
    Set<String> documented = new TreeSet<>(committed);
    Set<String> exposed = new TreeSet<>(live);
    if (!documented.equals(exposed)) {
      drift.add(what + ": documented " + documented + " but application exposes " + exposed);
    }
  }

  private static void compareValue(String what, Object committed, Object live, List<String> drift) {
    if (committed == null ? live != null : !committed.equals(live)) {
      drift.add(what + ": documented " + committed + " but application exposes " + live);
    }
  }

  private static Set<String> parameterNames(Object parameters) {
    Set<String> names = new LinkedHashSet<>();
    if (parameters instanceof List<?> list) {
      for (Object parameter : list) {
        Map<String, Object> p = map(parameter);
        names.add(p.get("in") + ":" + p.get("name") + ":required=" + p.get("required"));
      }
    }
    return names;
  }

  private static Set<String> union(Set<String> first, Set<String> second) {
    Set<String> union = new TreeSet<>(first);
    union.addAll(second);
    return union;
  }

  @SuppressWarnings("unchecked")
  private static Map<String, Object> map(Object value) {
    return value instanceof Map<?, ?> m ? (Map<String, Object>) m : Map.of();
  }

  private static List<String> list(Object value) {
    List<String> result = new ArrayList<>();
    if (value instanceof List<?> l) {
      for (Object item : l) {
        result.add(String.valueOf(item));
      }
    }
    return result;
  }
}
