"""
Architecture contract: Design.classes.layering_rules -> import-linter contracts -> tests/test_architecture.py.

The orchestrator writes and commits the test into the sandbox before the executor runs, so the agent under
test never authors its own architecture gate (policy.yaml: `architecture` gate = pytest on that file).
See docs/adr/0001-import-linter-for-the-architecture-gate.md.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from ..models import Design
from ..models.trace import Kind
from ..sandbox.git import GitSandbox
from .context import RunContext

CONTRACT_PATH = Path("tests") / "test_architecture.py"

_HEADER = '''"""Architecture contract generated by the orchestrator from Design.classes.layering_rules.

Spec version {spec_version}.

Regenerated whenever the design changes; do not edit by hand. Rules of the form "a -> b -> c" become
import-linter layer contracts: a higher layer may import a lower one, never the reverse (directly or through
a chain). Rules without "->" are recorded here for humans only: {prose!r}
"""

from __future__ import annotations
'''

_CHECKED = '''
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = """\\
{config}"""


def test_layering_rules(tmp_path: Path) -> None:
    from importlinter.cli import lint_imports

    sys.path.insert(0, str(ROOT / "src"))
    cfg = tmp_path / ".importlinter"
    cfg.write_text(CONFIG, encoding="utf-8")
    assert lint_imports(config_filename=str(cfg), no_cache=True) == 0, "layering rules violated (see output)"
'''

_UNCHECKED = '''

def test_no_machine_checkable_layering_rules() -> None:
    """The design declares no "a -> b -> c" rule, so there is nothing import-linter can enforce here."""
'''


def layer_chains(design: Design) -> list[list[str]]:
    chains = []
    for rule in design.classes.layering_rules:
        layers = [s.strip() for s in rule.split("->") if s.strip()]
        if len(layers) >= 2:
            chains.append(layers)
    return chains


def importlinter_config(design: Design) -> str | None:
    """INI config for import-linter, or None when the design has no machine-checkable rule."""
    chains = layer_chains(design)
    if not chains:
        return None
    roots = sorted({layer.split(".")[0] for chain in chains for layer in chain})
    out = ["[importlinter]", "root_packages =", *(f"    {r}" for r in roots), ""]
    for i, chain in enumerate(chains, start=1):
        out += [
            f"[importlinter:contract:layers_{i}]",
            f"name = {' -> '.join(chain)}",
            "type = layers",
            "layers =",
            *(
                f"    ({layer})" for layer in chain
            ),  # (optional): a layer that does not exist yet is not an error
            "",
        ]
    return "\n".join(out)


def render_architecture_test(design: Design) -> str:
    prose = [r for r in design.classes.layering_rules if "->" not in r]
    body = _HEADER.format(spec_version=design.spec_version, prose=prose)
    config = importlinter_config(design)
    return body + (_CHECKED.format(config=config) if config else _UNCHECKED)


async def write_architecture_contract(ctx: RunContext, git: GitSandbox, node_id: str) -> bool:
    """Write + commit the generated test when it changed. Python stack only; needs a Design in context."""
    design = ctx.get("design")
    if design is None or ctx.target_stack != "python":
        return False
    content = render_architecture_test(design)
    path = ctx.sandbox / CONTRACT_PATH
    current = await asyncio.to_thread(_read, path)
    if current == content:
        return False
    await asyncio.to_thread(_write, path, content)
    sha = await git.commit_task(
        "sdlc", f"architecture contract from design (spec v{design.spec_version})", ctx.run_id
    )
    ctx.emit(
        Kind.ARTIFACT_WRITTEN,
        node_id=node_id,
        actor="orchestrator",
        payload={
            "artifact": "architecture_contract",
            "path": str(CONTRACT_PATH),
            "contracts": len(layer_chains(design)),
            "commit": sha,
        },
    )
    return True


def _read(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.exists() else None


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
