"""
Architecture contract: Design.classes.layering_rules -> import-linter contracts -> tests/test_architecture.py.

The orchestrator writes and commits the test into the sandbox before the executor runs, so the agent under
test never authors its own architecture gate (policy.yaml: `architecture` gate = pytest on that file).
See docs/adr/0001-import-linter-for-the-architecture-gate.md.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path

from ..models import Design
from ..models.trace import Kind
from ..sandbox.git import GitSandbox
from .context import RunContext

CONTRACT_PATH = Path("tests") / "test_architecture.py"
JAVA_CONTRACT_PATH = Path("src/test/java/sdlc/ArchitectureTest.java")  # policy: -Dtest=ArchitectureTest

_HEADER = '''"""Architecture contract generated by the orchestrator from Design.classes.layering_rules.

Spec version {spec_version}.

Regenerated whenever the design changes; do not edit by hand. Rules of the form "a -> b -> c" become
import-linter layer contracts: a higher layer may import a lower one, never the reverse (directly or through
a chain). Rules without "->" are recorded here for humans only: {prose!r}
"""

from __future__ import annotations
'''

_CHECKED = '''
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = """\\
{config}"""


def test_layering_rules(tmp_path: Path) -> None:
    from importlinter.cli import lint_imports

    sys.path.insert(0, str(ROOT / "src"))
    cfg = tmp_path / ".importlinter"
    cfg.write_text(CONFIG, encoding="utf-8")
    assert lint_imports(config_filename=str(cfg), no_cache=True) == 0, "layering rules violated (see output)"
'''

_UNCHECKED = '''

def test_no_machine_checkable_layering_rules() -> None:
    """The design declares no "a -> b -> c" rule, so there is nothing import-linter can enforce here."""
'''


def layer_chains(design: Design) -> list[list[str]]:
    chains = []
    for rule in design.classes.layering_rules:
        layers = [s.strip() for s in rule.split("->") if s.strip()]
        if len(layers) >= 2:
            chains.append(layers)
    return chains


def importlinter_config(design: Design) -> str | None:
    """INI config for import-linter, or None when the design has no machine-checkable rule."""
    chains = layer_chains(design)
    if not chains:
        return None
    roots = sorted({layer.split(".")[0] for chain in chains for layer in chain})
    out = ["[importlinter]", "root_packages =", *(f"    {r}" for r in roots), ""]
    for i, chain in enumerate(chains, start=1):
        out += [
            f"[importlinter:contract:layers_{i}]",
            f"name = {' -> '.join(chain)}",
            "type = layers",
            "layers =",
            *(
                f"    ({layer})" for layer in chain
            ),  # (optional): a layer that does not exist yet is not an error
            "",
        ]
    return "\n".join(out)


_JAVA = """package sdlc;

// Architecture contract generated by the orchestrator from Design.classes.layering_rules.
// Spec version {spec_version}.
// Regenerated whenever the design changes; do not edit by hand. Rules of the form "a -> b -> c" are layer
// chains: a class whose package or name matches a layer must not import a class of a higher layer.
// Rules without "->" (for humans only): {prose}

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

class ArchitectureTest {{

  static final List<List<String>> CHAINS = List.of({chains});
  static final Pattern PKG = Pattern.compile("^\\\\s*package\\\\s+([\\\\w.]+)\\\\s*;", Pattern.MULTILINE);
  static final Pattern IMP =
      Pattern.compile("^\\\\s*import\\\\s+(?:static\\\\s+)?([\\\\w.]+)\\\\s*;", Pattern.MULTILINE);

  @Test
  void layeringRules() throws IOException {{
    Path root = Path.of("src/main/java");
    if (!Files.isDirectory(root) || CHAINS.isEmpty()) {{
      return;
    }}
    Map<String, List<String>> imports = new HashMap<>();
    try (Stream<Path> files = Files.walk(root)) {{
      for (Path p : files.filter(f -> f.toString().endsWith(".java")).toList()) {{
        String src = Files.readString(p);
        Matcher pm = PKG.matcher(src);
        String pkg = pm.find() ? pm.group(1) : "";
        String fqcn = pkg + "." + p.getFileName().toString().replace(".java", "");
        List<String> imps = new ArrayList<>();
        Matcher im = IMP.matcher(src);
        while (im.find()) {{
          imps.add(im.group(1));
        }}
        imports.put(fqcn, imps);
      }}
    }}
    List<String> violations = new ArrayList<>();
    for (List<String> chain : CHAINS) {{
      for (Map.Entry<String, List<String>> e : imports.entrySet()) {{
        int from = layerOf(e.getKey(), chain);
        if (from < 0) {{
          continue;
        }}
        for (String imp : e.getValue()) {{
          int to = layerOf(imp, chain);
          if (to >= 0 && to < from) {{
            violations.add(
                e.getKey() + " -> " + imp + " (" + chain.get(from) + " must not depend on "
                    + chain.get(to) + ")");
          }}
        }}
      }}
    }}
    assertTrue(violations.isEmpty(), "layering rules violated:\\n" + String.join("\\n", violations));
  }}

  static int layerOf(String fqcn, List<String> chain) {{
    String lower = fqcn.toLowerCase();
    for (int i = 0; i < chain.size(); i++) {{
      String layer = chain.get(i);
      if (lower.contains("." + layer + ".") || lower.endsWith("." + layer) || lower.endsWith(layer)) {{
        return i;
      }}
    }}
    return -1;
  }}
}}
"""


def _java_layer(token: str) -> str:
    """'Repository -> Domain; dependencies point inward' -> 'domain' (a package/class-name fragment)."""
    head = re.split(r"[;,(]", token, maxsplit=1)[0].strip()
    return head.split()[-1].lower().split(".")[-1] if head else ""


def render_architecture_test_java(design: Design) -> str:
    chains = [[_java_layer(t) for t in chain if _java_layer(t)] for chain in layer_chains(design)]
    chains = [c for c in chains if len(c) >= 2]
    prose = [r for r in design.classes.layering_rules if "->" not in r]
    java_chains = ", ".join("List.of(" + ", ".join(f'"{layer}"' for layer in c) + ")" for c in chains)
    return _JAVA.format(spec_version=design.spec_version, prose=prose, chains=java_chains)


def render_architecture_test(design: Design) -> str:
    prose = [r for r in design.classes.layering_rules if "->" not in r]
    body = _HEADER.format(spec_version=design.spec_version, prose=prose)
    config = importlinter_config(design)
    return body + (_CHECKED.format(config=config) if config else _UNCHECKED)


async def write_architecture_contract(ctx: RunContext, git: GitSandbox, node_id: str) -> bool:
    """Write + commit the generated test when it changed. Python stack only; needs a Design in context."""
    design = ctx.get("design")
    if design is None or ctx.target_stack not in ("python", "java"):
        return False
    if ctx.target_stack == "java":
        content, rel = render_architecture_test_java(design), JAVA_CONTRACT_PATH
    else:
        content, rel = render_architecture_test(design), CONTRACT_PATH
    path = ctx.sandbox / rel
    current = await asyncio.to_thread(_read, path)
    if current == content:
        return False
    await asyncio.to_thread(_write, path, content)
    sha = await git.commit_task(
        "sdlc", f"architecture contract from design (spec v{design.spec_version})", ctx.run_id
    )
    ctx.emit(
        Kind.ARTIFACT_WRITTEN,
        node_id=node_id,
        actor="orchestrator",
        payload={
            "artifact": "architecture_contract",
            "path": str(rel),
            "contracts": len(layer_chains(design)),
            "commit": sha,
        },
    )
    return True


def _read(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.exists() else None


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
